<center>
<form action="Realocacao/edit" method="POST" id="fRelEdit" class="form" >
    <input type="hidden" name="idrealocacao" id="idrealocacao" value="{$obj.idrealocacao}"/>
    <input type="hidden" name="instalacoes_idinstalacoes" id="instalacoes_idinstalacoes" value="{$obj.instalacoes_idinstalacoes}"/>
   <fieldset>
            <legend>Realocação</legend>
            <br />
    <div style="float:left; margin-right:5px; padding:5px;width:50%">
        <label for='data'>Novo Endereço</label>
        <hr/>
        <table class="tbForm">
            <tr>
                <td>
                    <label for="latitude">Latitude</label>
                </td>
                <td>
                    <input type="text" name="latitude" id="latitude" size="10" value="{$obj.latitude}"   />
                </td>
                <td>
                    <label for="longitude">Longitude</label>
                </td>
                <td>
                    <input type="text" name="longitude" id="longitude" size="10" value="{$obj.longitude}"   />
                </td>
            </tr>
            <tr>    
                <td>
                    <label for="cep">CEP</label>
                </td>
                <td >
                    <input type="text" name="cep" id="cep" size="10" value="{$obj.cep}" />
                </td>
                <td>
                    <label for="cep">Código de Área</label>
                </td>
                <td >
                    <input type="text" name="cod_area" id="cod_area" size="10"  value="{$obj.cod_area}"/>
                </td>
            </tr>
            <tr>    
                <td>
                    <label for="tel">Cidade </label>
                </td>
                <td>
                     <select name="cidade" id="cidade">
                                                    <option value="Abadia dos Dourados">Abadia dos Dourados</option>
                                                    <option value="Abre Campo">Abre Campo</option>
                                                    <option value="Acucna">Acucna</option>
                                                    <option value="Aguanil">Aguanil</option>
                                                    <option value="AguasA FormosasA">AguasA FormosasA</option>
                                                    <option value="Aguas Vermelhas">Aguas Vermelhas</option>
                                                    <option value="Aimores">Aimores</option>
                                                    <option value="Aiuruoca">Aiuruoca</option>
                                                    <option value="Alagoa">Alagoa</option>
                                                    <option value="Albertina">Albertina</option>
                                                    <option value="Alem Paraiba">Alem Paraiba</option>
                                                    <option value="Alfenas">Alfenas</option>
                                                    <option value="Alfredo Vasconcelos">Alfredo Vasconcelos</option>
                                                    <option value="Almenara">Almenara</option>
                                                    <option value="Alpercata">Alpercata</option>
                                                    <option value="Alpinopolis">Alpinopolis</option>
                                                    <option value="Alterosa">Alterosa</option>
                                                    <option value="Alto Caparao">Alto Caparao</option>
                                                    <option value="Alto Jequitiba">Alto Jequitiba</option>
                                                    <option value="Alto Rio Doce">Alto Rio Doce</option>
                                                    <option value="Alvarenga">Alvarenga</option>
                                                    <option value="Alvinopolis">Alvinopolis</option>
                                                    <option value="Alvorada de Minas">Alvorada de Minas</option>
                                                    <option value="Amparo do Serra">Amparo do Serra</option>
                                                    <option value="Andradas">Andradas</option>
                                                    <option value="Andrelandia">Andrelandia</option>
                                                    <option value="Angelandia">Angelandia</option>
                                                    <option value="Antonio Carlos">Antonio Carlos</option>
                                                    <option value="Antonio Dias">Antonio Dias</option>
                                                    <option value="Antonio Prado de Minas">Antonio Prado de Minas</option>
                                                    <option value="Aracai">Aracai</option>
                                                    <option value="Aracitaba">Aracitaba</option>
                                                    <option value="Aracuai">Aracuai</option>
                                                    <option value="Araguari">Araguari</option>
                                                    <option value="Arantina">Arantina</option>
                                                    <option value="Araponga">Araponga</option>
                                                    <option value="Arapora">Arapora</option>
                                                    <option value="Arapua">Arapua</option>
                                                    <option value="Araujos">Araujos</option>
                                                    <option value="Araxa">Araxa</option>
                                                    <option value="Arceburgo">Arceburgo</option>
                                                    <option value="Arcos">Arcos</option>
                                                    <option value="Areado">Areado</option>
                                                    <option value="Argirita">Argirita</option>
                                                    <option value="Aricanduva">Aricanduva</option>
                                                    <option value="Arinos">Arinos</option>
                                                    <option value="Astolfo Dutra">Astolfo Dutra</option>
                                                    <option value="Ataleia">Ataleia</option>
                                                    <option value="Augusto de Lima">Augusto de Lima</option>
                                                    <option value="Baependi">Baependi</option>
                                                    <option value="Baldim">Baldim</option>
                                                    <option value="Bambui">Bambui</option>
                                                    <option value="Bandeira do Sul">Bandeira do Sul</option>
                                                    <option value="Bandeira">Bandeira</option>
                                                    <option value="Barao de Cocais">Barao de Cocais</option>
                                                    <option value="Barao de Monte Alto">Barao de Monte Alto</option>
                                                    <option value="Barbacena">Barbacena</option>
                                                    <option value="Barra Longa">Barra Longa</option>
                                                    <option value="Barroso">Barroso</option>
                                                    <option value="Bela Vista de Minas">Bela Vista de Minas</option>
                                                    <option value="Belmiro Braga">Belmiro Braga</option>
                                                    <option value="Belo Horizonte">Belo Horizonte</option>
                                                    <option value="Belo Oriente">Belo Oriente</option>
                                                    <option value="Belo Vale">Belo Vale</option>
                                                    <option value="Berilo">Berilo</option>
                                                    <option value="Berizal">Berizal</option>
                                                    <option value="Bertopolis">Bertopolis</option>
                                                    <option value="Betim">Betim</option>
                                                    <option value="Bias Fortes">Bias Fortes</option>
                                                    <option value="Bicas">Bicas</option>
                                                    <option value="Biquinhas">Biquinhas</option>
                                                    <option value="Boa Esperanca">Boa Esperanca</option>
                                                    <option value="Bocaina de Minas">Bocaina de Minas</option>
                                                    <option value="Bocaiuva">Bocaiuva</option>
                                                    <option value="Bom Despacho">Bom Despacho</option>
                                                    <option value="Bom Jardim de Minas">Bom Jardim de Minas</option>
                                                    <option value="Bom Jesus da Penha">Bom Jesus da Penha</option>
                                                    <option value="Bom Jesus do Amparo">Bom Jesus do Amparo</option>
                                                    <option value="Bom Jesus do Galho">Bom Jesus do Galho</option>
                                                    <option value="Bom Repouso">Bom Repouso</option>
                                                    <option value="Bom Sucesso">Bom Sucesso</option>
                                                    <option value="Bonfim">Bonfim</option>
                                                    <option value="Bonfinopolis de Minas">Bonfinopolis de Minas</option>
                                                    <option value="Bonito de Minas">Bonito de Minas</option>
                                                    <option value="Borda da Mata">Borda da Mata</option>
                                                    <option value="Botelhos">Botelhos</option>
                                                    <option value="Botumirim">Botumirim</option>
                                                    <option value="Bras Pires">Bras Pires</option>
                                                    <option value="Brasilandia de Minas">Brasilandia de Minas</option>
                                                    <option value="Brasilia de Minas">Brasilia de Minas</option>
                                                    <option value="Brasopolis">Brasopolis</option>
                                                    <option value="Braunas">Braunas</option>
                                                    <option value="Brumadinho">Brumadinho</option>
                                                    <option value="Bueno Brandao">Bueno Brandao</option>
                                                    <option value="Buenopolis">Buenopolis</option>
                                                    <option value="Bugre">Bugre</option>
                                                    <option value="Buritis">Buritis</option>
                                                    <option value="Buritizeiro">Buritizeiro</option>
                                                    <option value="Cabeceira Grande">Cabeceira Grande</option>
                                                    <option value="Cabo Verde">Cabo Verde</option>
                                                    <option value="Cachoeira Dourada">Cachoeira Dourada</option>
                                                    <option value="Cachoeira da Prata">Cachoeira da Prata</option>
                                                    <option value="Cachoeira de Minas">Cachoeira de Minas</option>
                                                    <option value="Cachoeira de Pajeu">Cachoeira de Pajeu</option>
                                                    <option value="Caetanopolis">Caetanopolis</option>
                                                    <option value="Caete">Caete</option>
                                                    <option value="Caiana">Caiana</option>
                                                    <option value="Cajuri">Cajuri</option>
                                                    <option value="Caldas">Caldas</option>
                                                    <option value="Camacho">Camacho</option>
                                                    <option value="Camanducaia">Camanducaia</option>
                                                    <option value="Cambui">Cambui</option>
                                                    <option value="Cambuquira">Cambuquira</option>
                                                    <option value="Campanario">Campanario</option>
                                                    <option value="Campanha">Campanha</option>
                                                    <option value="Campestre">Campestre</option>
                                                    <option value="Campina Verde">Campina Verde</option>
                                                    <option value="Campo Azul">Campo Azul</option>
                                                    <option value="Campo Belo">Campo Belo</option>
                                                    <option value="Campo Florido">Campo Florido</option>
                                                    <option value="Campo do Meio">Campo do Meio</option>
                                                    <option value="Campos Altos">Campos Altos</option>
                                                    <option value="Campos Gerais">Campos Gerais</option>
                                                    <option value="Cana Verde">Cana Verde</option>
                                                    <option value="Canaa">Canaa</option>
                                                    <option value="Canapolis">Canapolis</option>
                                                    <option value="Candeias">Candeias</option>
                                                    <option value="Cantagalo">Cantagalo</option>
                                                    <option value="Caparao">Caparao</option>
                                                    <option value="Capela Nova">Capela Nova</option>
                                                    <option value="Capelinha">Capelinha</option>
                                                    <option value="Capetinga">Capetinga</option>
                                                    <option value="Capim Branco">Capim Branco</option>
                                                    <option value="Capinopolis">Capinopolis</option>
                                                    <option value="Capitao Andrade">Capitao Andrade</option>
                                                    <option value="Capitao Eneas">Capitao Eneas</option>
                                                    <option value="Capitolio">Capitolio</option>
                                                    <option value="Caputira">Caputira</option>
                                                    <option value="Carai">Carai</option>
                                                    <option value="Caranaiba">Caranaiba</option>
                                                    <option value="Carandai">Carandai</option>
                                                    <option value="Carangola">Carangola</option>
                                                    <option value="Caratinga">Caratinga</option>
                                                    <option value="Carbonita">Carbonita</option>
                                                    <option value="Careacu">Careacu</option>
                                                    <option value="Carlos Chagas">Carlos Chagas</option>
                                                    <option value="Carmesia">Carmesia</option>
                                                    <option value="Carmo da Cachoeira">Carmo da Cachoeira</option>
                                                    <option value="Carmo da Mata">Carmo da Mata</option>
                                                    <option value="Carmo de Minas">Carmo de Minas</option>
                                                    <option value="Carmo do Cajuru">Carmo do Cajuru</option>
                                                    <option value="Carmo do Paranaiba">Carmo do Paranaiba</option>
                                                    <option value="Carmo do Rio Claro">Carmo do Rio Claro</option>
                                                    <option value="Carmopolis de Minas">Carmopolis de Minas</option>
                                                    <option value="Carneirinho">Carneirinho</option>
                                                    <option value="Carrancas">Carrancas</option>
                                                    <option value="Carvalhopolis">Carvalhopolis</option>
                                                    <option value="Carvalhos">Carvalhos</option>
                                                    <option value="Casa Grande">Casa Grande</option>
                                                    <option value="Cascalho Rico">Cascalho Rico</option>
                                                    <option value="Cassia">Cassia</option>
                                                    <option value="Cataguases">Cataguases</option>
                                                    <option value="Catas Altas da Noruega">Catas Altas da Noruega</option>
                                                    <option value="Catas Altas">Catas Altas</option>
                                                    <option value="Catuji">Catuji</option>
                                                    <option value="Catuti">Catuti</option>
                                                    <option value="Caxambu">Caxambu</option>
                                                    <option value="Cedro do Abaete">Cedro do Abaete</option>
                                                    <option value="Central de Minas">Central de Minas</option>
                                                    <option value="Centralina">Centralina</option>
                                                    <option value="Chacara">Chacara</option>
                                                    <option value="Chale">Chale</option>
                                                    <option value="Chapada Gaucha">Chapada Gaucha</option>
                                                    <option value="Chapada do Norte">Chapada do Norte</option>
                                                    <option value="Chiador">Chiador</option>
                                                    <option value="Cipotanea">Cipotanea</option>
                                                    <option value="Claraval">Claraval</option>
                                                    <option value="Claro dos Pocoes">Claro dos Pocoes</option>
                                                    <option value="Claudio">Claudio</option>
                                                    <option value="Coimbra">Coimbra</option>
                                                    <option value="Coluna">Coluna</option>
                                                    <option value="Comendador Gomes">Comendador Gomes</option>
                                                    <option value="Comercinho">Comercinho</option>
                                                    <option value="Conceicao da Aparecida">Conceicao da Aparecida</option>
                                                    <option value="Conceicao da Barra de Minas">Conceicao da Barra de Minas</option>
                                                    <option value="Conceicao das Alagoas">Conceicao das Alagoas</option>
                                                    <option value="Conceicao das Pedras">Conceicao das Pedras</option>
                                                    <option value="Conceicao de Ipanema">Conceicao de Ipanema</option>
                                                    <option value="Conceicao do Mato Dentro">Conceicao do Mato Dentro</option>
                                                    <option value="Conceicao do Para">Conceicao do Para</option>
                                                    <option value="Conceicao do Rio Verde">Conceicao do Rio Verde</option>
                                                    <option value="Conceicao dos Ouros">Conceicao dos Ouros</option>
                                                    <option value="Conego Marinho">Conego Marinho</option>
                                                    <option value="Confins">Confins</option>
                                                    <option value="Congonhal">Congonhal</option>
                                                    <option value="Congonhas do Norte">Congonhas do Norte</option>
                                                    <option value="Congonhas">Congonhas</option>
                                                    <option value="Conquista">Conquista</option>
                                                    <option value="Conselheiro Lafaiete">Conselheiro Lafaiete</option>
                                                    <option value="Conselheiro Pena">Conselheiro Pena</option>
                                                    <option value="Consolacao">Consolacao</option>
                                                    <option value="Contagem">Contagem</option>
                                                    <option value="Coqueiral">Coqueiral</option>
                                                    <option value="Coracao de Jesus">Coracao de Jesus</option>
                                                    <option value="Cordisburgo">Cordisburgo</option>
                                                    <option value="Cordislandia">Cordislandia</option>
                                                    <option value="Corinto">Corinto</option>
                                                    <option value="Coroaci">Coroaci</option>
                                                    <option value="Coromandel">Coromandel</option>
                                                    <option value="Coronel Fabriciano">Coronel Fabriciano</option>
                                                    <option value="Coronel Murta">Coronel Murta</option>
                                                    <option value="Coronel Pacheco">Coronel Pacheco</option>
                                                    <option value="Coronel Xavier Chaves">Coronel Xavier Chaves</option>
                                                    <option value="Corrego Danta">Corrego Danta</option>
                                                    <option value="Corrego Fundo">Corrego Fundo</option>
                                                    <option value="Corrego Novo">Corrego Novo</option>
                                                    <option value="Corrego do Bom Jesus">Corrego do Bom Jesus</option>
                                                    <option value="Couto de Magalhaes de Minas">Couto de Magalhaes de Minas</option>
                                                    <option value="Crisolita">Crisolita</option>
                                                    <option value="Cristais">Cristais</option>
                                                    <option value="Cristalia">Cristalia</option>
                                                    <option value="Cristiano Otoni">Cristiano Otoni</option>
                                                    <option value="Cristina">Cristina</option>
                                                    <option value="Crucilandia">Crucilandia</option>
                                                    <option value="Cruzeiro da Fortaleza">Cruzeiro da Fortaleza</option>
                                                    <option value="Cruzilia">Cruzilia</option>
                                                    <option value="Cuparaque">Cuparaque</option>
                                                    <option value="Curral de Dentro">Curral de Dentro</option>
                                                    <option value="Curvelo">Curvelo</option>
                                                    <option value="Datas">Datas</option>
                                                    <option value="Delfim Moreira">Delfim Moreira</option>
                                                    <option value="Delfinopolis">Delfinopolis</option>
                                                    <option value="Delta">Delta</option>
                                                    <option value="Descoberto">Descoberto</option>
                                                    <option value="Desterro de Entre Rios">Desterro de Entre Rios</option>
                                                    <option value="Desterro do Melo">Desterro do Melo</option>
                                                    <option value="Diamantina">Diamantina</option>
                                                    <option value="Diogo de Vasconcelos">Diogo de Vasconcelos</option>
                                                    <option value="Dionisio">Dionisio</option>
                                                    <option value="Divinesia">Divinesia</option>
                                                    <option value="Divino das Laranjeiras">Divino das Laranjeiras</option>
                                                    <option value="Divino">Divino</option>
                                                    <option value="Divinolandia de Minas">Divinolandia de Minas</option>
                                                    <option value="Divinopolis">Divinopolis</option>
                                                    <option value="Divisa Alegre">Divisa Alegre</option>
                                                    <option value="Divisa Nova">Divisa Nova</option>
                                                    <option value="Divisopolis">Divisopolis</option>
                                                    <option value="Dom Bosco">Dom Bosco</option>
                                                    <option value="Dom Cavati">Dom Cavati</option>
                                                    <option value="Dom Joaquim">Dom Joaquim</option>
                                                    <option value="Dom Silverio">Dom Silverio</option>
                                                    <option value="Dom Vicoso">Dom Vicoso</option>
                                                    <option value="Dona Euzebia">Dona Euzebia</option>
                                                    <option value="Dores de Campos">Dores de Campos</option>
                                                    <option value="Dores de Guanhaes">Dores de Guanhaes</option>
                                                    <option value="Dores do Indaia">Dores do Indaia</option>
                                                    <option value="Dores do Turvo">Dores do Turvo</option>
                                                    <option value="Doresopolis">Doresopolis</option>
                                                    <option value="Douradoquara">Douradoquara</option>
                                                    <option value="Durande">Durande</option>
                                                    <option value="Eloi Mendes">Eloi Mendes</option>
                                                    <option value="Engenheiro Caldas">Engenheiro Caldas</option>
                                                    <option value="Engenheiro Navarro">Engenheiro Navarro</option>
                                                    <option value="Entre Folhas">Entre Folhas</option>
                                                    <option value="Entre Rios de Minas">Entre Rios de Minas</option>
                                                    <option value="Ervalia">Ervalia</option>
                                                    <option value="Esmeraldas">Esmeraldas</option>
                                                    <option value="Espera Feliz">Espera Feliz</option>
                                                    <option value="Espinosa">Espinosa</option>
                                                    <option value="Espirito Santo do Dourado">Espirito Santo do Dourado</option>
                                                    <option value="Estiva">Estiva</option>
                                                    <option value="Estrela Dalva">Estrela Dalva</option>
                                                    <option value="Estrela do Indaia">Estrela do Indaia</option>
                                                    <option value="Estrela do Sul">Estrela do Sul</option>
                                                    <option value="Eugenopolis">Eugenopolis</option>
                                                    <option value="Ewbank da Camara">Ewbank da Camara</option>
                                                    <option value="Extrema">Extrema</option>
                                                    <option value="Fama">Fama</option>
                                                    <option value="Faria Lemos">Faria Lemos</option>
                                                    <option value="Felicio dos Santos">Felicio dos Santos</option>
                                                    <option value="Felisburgo">Felisburgo</option>
                                                    <option value="Felixlandia">Felixlandia</option>
                                                    <option value="Fernandes Tourinho">Fernandes Tourinho</option>
                                                    <option value="Ferros">Ferros</option>
                                                    <option value="Fervedouro">Fervedouro</option>
                                                    <option value="Florestal">Florestal</option>
                                                    <option value="Formiga">Formiga</option>
                                                    <option value="Formoso">Formoso</option>
                                                    <option value="Fortaleza de Minas">Fortaleza de Minas</option>
                                                    <option value="Fortuna de Minas">Fortuna de Minas</option>
                                                    <option value="Francisco Badaro">Francisco Badaro</option>
                                                    <option value="Francisco Dumont">Francisco Dumont</option>
                                                    <option value="Francisco Sa">Francisco Sa</option>
                                                    <option value="Franciscopolis">Franciscopolis</option>
                                                    <option value="Frei Gaspar">Frei Gaspar</option>
                                                    <option value="Frei Inocencio">Frei Inocencio</option>
                                                    <option value="Frei Lagonegro">Frei Lagonegro</option>
                                                    <option value="Fronteira dos Vales">Fronteira dos Vales</option>
                                                    <option value="Fronteira">Fronteira</option>
                                                    <option value="Fruta de Leite">Fruta de Leite</option>
                                                    <option value="Frutal">Frutal</option>
                                                    <option value="Funilandia">Funilandia</option>
                                                    <option value="Galileia">Galileia</option>
                                                    <option value="Gameleiras">Gameleiras</option>
                                                    <option value="Glaucilandia">Glaucilandia</option>
                                                    <option value="Goiabeira">Goiabeira</option>
                                                    <option value="Goiana">Goiana</option>
                                                    <option value="Goncalves">Goncalves</option>
                                                    <option value="Gonzaga">Gonzaga</option>
                                                    <option value="Gouvea">Gouvea</option>
                                                    <option value="Governador Valadares">Governador Valadares</option>
                                                    <option value="Grao Mogol">Grao Mogol</option>
                                                    <option value="Grupiara">Grupiara</option>
                                                    <option value="Guanhaes">Guanhaes</option>
                                                    <option value="Guape">Guape</option>
                                                    <option value="Guaraciaba">Guaraciaba</option>
                                                    <option value="Guaraciama">Guaraciama</option>
                                                    <option value="Guaranesia">Guaranesia</option>
                                                    <option value="Guarani">Guarani</option>
                                                    <option value="Guarara">Guarara</option>
                                                    <option value="Guarda-Mor">Guarda-Mor</option>
                                                    <option value="Guaxupe">Guaxupe</option>
                                                    <option value="Guidoval">Guidoval</option>
                                                    <option value="Guimarania">Guimarania</option>
                                                    <option value="Guiricema">Guiricema</option>
                                                    <option value="Gurinhata">Gurinhata</option>
                                                    <option value="Heliodora">Heliodora</option>
                                                    <option value="Iapu">Iapu</option>
                                                    <option value="Ibertioga">Ibertioga</option>
                                                    <option value="Ibia">Ibia</option>
                                                    <option value="Ibiai">Ibiai</option>
                                                    <option value="Ibiracatu">Ibiracatu</option>
                                                    <option value="Ibiraci">Ibiraci</option>
                                                    <option value="Ibirite">Ibirite</option>
                                                    <option value="Ibitiura de Minas">Ibitiura de Minas</option>
                                                    <option value="Ibituruna">Ibituruna</option>
                                                    <option value="Icarai de Minas">Icarai de Minas</option>
                                                    <option value="Igarape">Igarape</option>
                                                    <option value="Igaratinga">Igaratinga</option>
                                                    <option value="Iguatama">Iguatama</option>
                                                    <option value="Ijaci">Ijaci</option>
                                                    <option value="Ilicinea">Ilicinea</option>
                                                    <option value="Imbe de Minas">Imbe de Minas</option>
                                                    <option value="Inconfidentes">Inconfidentes</option>
                                                    <option value="Indaiabira">Indaiabira</option>
                                                    <option value="Indianopolis">Indianopolis</option>
                                                    <option value="Ingai">Ingai</option>
                                                    <option value="Inhapim">Inhapim</option>
                                                    <option value="Inhauma">Inhauma</option>
                                                    <option value="Inimutaba">Inimutaba</option>
                                                    <option value="Ipaba">Ipaba</option>
                                                    <option value="Ipanema">Ipanema</option>
                                                    <option value="Ipatinga">Ipatinga</option>
                                                    <option value="Ipiacu">Ipiacu</option>
                                                    <option value="Ipuiuna">Ipuiuna</option>
                                                    <option value="Irai de Minas">Irai de Minas</option>
                                                    <option value="Itabira">Itabira</option>
                                                    <option value="Itabirinha de Mantena">Itabirinha de Mantena</option>
                                                    <option value="Itabirito">Itabirito</option>
                                                    <option value="Itacambira">Itacambira</option>
                                                    <option value="Itacarambi">Itacarambi</option>
                                                    <option value="Itaguara">Itaguara</option>
                                                    <option value="Itaipe">Itaipe</option>
                                                    <option value="Itajuba">Itajuba</option>
                                                    <option value="Itamarandiba">Itamarandiba</option>
                                                    <option value="Itamarati de Minas">Itamarati de Minas</option>
                                                    <option value="Itambacuri">Itambacuri</option>
                                                    <option value="Itambe do Mato Dentro">Itambe do Mato Dentro</option>
                                                    <option value="Itamogi">Itamogi</option>
                                                    <option value="Itamonte">Itamonte</option>
                                                    <option value="Itanhandu">Itanhandu</option>
                                                    <option value="Itanhomi">Itanhomi</option>
                                                    <option value="Itaobim">Itaobim</option>
                                                    <option value="Itapagipe">Itapagipe</option>
                                                    <option value="Itapecerica">Itapecerica</option>
                                                    <option value="Itapeva">Itapeva</option>
                                                    <option value="Itatiaiucu">Itatiaiucu</option>
                                                    <option value="Itau de Minas">Itau de Minas</option>
                                                    <option value="Itauna">Itauna</option>
                                                    <option value="Itaverava">Itaverava</option>
                                                    <option value="Itinga">Itinga</option>
                                                    <option value="Itueta">Itueta</option>
                                                    <option value="Ituiutaba">Ituiutaba</option>
                                                    <option value="Itumirim">Itumirim</option>
                                                    <option value="Iturama">Iturama</option>
                                                    <option value="Itutinga">Itutinga</option>
                                                    <option value="Jaboticatubas">Jaboticatubas</option>
                                                    <option value="Jacinto">Jacinto</option>
                                                    <option value="Jacui">Jacui</option>
                                                    <option value="Jacutinga">Jacutinga</option>
                                                    <option value="Jaguaracu">Jaguaracu</option>
                                                    <option value="Jaiba">Jaiba</option>
                                                    <option value="Jampruca">Jampruca</option>
                                                    <option value="Janauba">Janauba</option>
                                                    <option value="Januaria">Januaria</option>
                                                    <option value="Japaraiba">Japaraiba</option>
                                                    <option value="Japonvar">Japonvar</option>
                                                    <option value="Jeceaba">Jeceaba</option>
                                                    <option value="Jenipapo de Minas">Jenipapo de Minas</option>
                                                    <option value="Jequeri">Jequeri</option>
                                                    <option value="Jequitai">Jequitai</option>
                                                    <option value="Jequitiba">Jequitiba</option>
                                                    <option value="Jequitinhonha">Jequitinhonha</option>
                                                    <option value="Jesuania">Jesuania</option>
                                                    <option value="Joaima">Joaima</option>
                                                    <option value="Joanesia">Joanesia</option>
                                                    <option value="Joao Monlevade">Joao Monlevade</option>
                                                    <option value="Joao Pinheiro">Joao Pinheiro</option>
                                                    <option value="Joaquim Felicio">Joaquim Felicio</option>
                                                    <option value="Jordania">Jordania</option>
                                                    <option value="Jose Goncalves de Minas">Jose Goncalves de Minas</option>
                                                    <option value="Jose Raydan">Jose Raydan</option>
                                                    <option value="Josenopolis">Josenopolis</option>
                                                    <option value="Juatuba">Juatuba</option>
                                                    <option value="Juiz de Fora">Juiz de Fora</option>
                                                    <option value="Juramento">Juramento</option>
                                                    <option value="Juruaia">Juruaia</option>
                                                    <option value="Juvenilia">Juvenilia</option>
                                                    <option value="Ladainha">Ladainha</option>
                                                    <option value="Lagamar">Lagamar</option>
                                                    <option value="Lagoa Dourada">Lagoa Dourada</option>
                                                    <option value="Lagoa Formosa">Lagoa Formosa</option>
                                                    <option value="Lagoa Grande">Lagoa Grande</option>
                                                    <option value="Lagoa Santa">Lagoa Santa</option>
                                                    <option value="Lagoa da Prata">Lagoa da Prata</option>
                                                    <option value="Lagoa dos Patos">Lagoa dos Patos</option>
                                                    <option value="Lagoas">Lagoas</option>
                                                    <option value="Lajinha">Lajinha</option>
                                                    <option value="Lambari">Lambari</option>
                                                    <option value="Lamim">Lamim</option>
                                                    <option value="Laranjal">Laranjal</option>
                                                    <option value="Lassance">Lassance</option>
                                                    <option value="Lavras">Lavras</option>
                                                    <option value="Leandro Ferreira">Leandro Ferreira</option>
                                                    <option value="Leme do Prado">Leme do Prado</option>
                                                    <option value="Leopoldina">Leopoldina</option>
                                                    <option value="Liberdade">Liberdade</option>
                                                    <option value="Lima Duarte">Lima Duarte</option>
                                                    <option value="Limeira do Oeste">Limeira do Oeste</option>
                                                    <option value="Lontra">Lontra</option>
                                                    <option value="Luisburgo">Luisburgo</option>
                                                    <option value="Luislandia">Luislandia</option>
                                                    <option value="Luminarias">Luminarias</option>
                                                    <option value="Luz">Luz</option>
                                                    <option value="Machacalis">Machacalis</option>
                                                    <option value="Machado">Machado</option>
                                                    <option value="Madre de Deus de Minas">Madre de Deus de Minas</option>
                                                    <option value="Malacacheta">Malacacheta</option>
                                                    <option value="Mamonas">Mamonas</option>
                                                    <option value="Manga">Manga</option>
                                                    <option value="Manhuacu">Manhuacu</option>
                                                    <option value="Manhumirim">Manhumirim</option>
                                                    <option value="Mantena">Mantena</option>
                                                    <option value="Mar de Espanha">Mar de Espanha</option>
                                                    <option value="Maravilhas">Maravilhas</option>
                                                    <option value="Maria da Fe">Maria da Fe</option>
                                                    <option value="Mariana">Mariana</option>
                                                    <option value="Marilac">Marilac</option>
                                                    <option value="Mario Campos">Mario Campos</option>
                                                    <option value="Maripa de Minas">Maripa de Minas</option>
                                                    <option value="Marlieria">Marlieria</option>
                                                    <option value="Marmelopolis">Marmelopolis</option>
                                                    <option value="Martinho Campos">Martinho Campos</option>
                                                    <option value="Martins Soares">Martins Soares</option>
                                                    <option value="Mata Verde">Mata Verde</option>
                                                    <option value="Materlandia">Materlandia</option>
                                                    <option value="Mateus Leme">Mateus Leme</option>
                                                    <option value="Mathias Lobato">Mathias Lobato</option>
                                                    <option value="Matias Barbosa">Matias Barbosa</option>
                                                    <option value="Matias Cardoso">Matias Cardoso</option>
                                                    <option value="Matipo">Matipo</option>
                                                    <option value="Mato Verde">Mato Verde</option>
                                                    <option value="Matozinhos">Matozinhos</option>
                                                    <option value="Matutina">Matutina</option>
                                                    <option value="Medeiros">Medeiros</option>
                                                    <option value="Medina">Medina</option>
                                                    <option value="Mendes Pimentel">Mendes Pimentel</option>
                                                    <option value="Merces">Merces</option>
                                                    <option value="Mesquita">Mesquita</option>
                                                    <option value="Minas Novas">Minas Novas</option>
                                                    <option value="Minduri">Minduri</option>
                                                    <option value="Mirabela">Mirabela</option>
                                                    <option value="Miradouro">Miradouro</option>
                                                    <option value="Mirai">Mirai</option>
                                                    <option value="Miravania">Miravania</option>
                                                    <option value="Moeda">Moeda</option>
                                                    <option value="Moema">Moema</option>
                                                    <option value="Monjolos">Monjolos</option>
                                                    <option value="Monsenhor Paulo">Monsenhor Paulo</option>
                                                    <option value="Montalvania">Montalvania</option>
                                                    <option value="Monte Alegre de Minas">Monte Alegre de Minas</option>
                                                    <option value="Monte Azul">Monte Azul</option>
                                                    <option value="Monte Belo">Monte Belo</option>
                                                    <option value="Monte Carmelo">Monte Carmelo</option>
                                                    <option value="Monte Formoso">Monte Formoso</option>
                                                    <option value="Monte Santo de Minas">Monte Santo de Minas</option>
                                                    <option value="Monte Siao">Monte Siao</option>
                                                    <option value="Montes Claros">Montes Claros</option>
                                                    <option value="Montezuma">Montezuma</option>
                                                    <option value="Morada Nova de Minas">Morada Nova de Minas</option>
                                                    <option value="Morro da Garca">Morro da Garca</option>
                                                    <option value="Morro do Pilar">Morro do Pilar</option>
                                                    <option value="Munhoz">Munhoz</option>
                                                    <option value="Muriae">Muriae</option>
                                                    <option value="Mutum">Mutum</option>
                                                    <option value="Muzambinho">Muzambinho</option>
                                                    <option value="Nacip Raydan">Nacip Raydan</option>
                                                    <option value="Nanuque">Nanuque</option>
                                                    <option value="Naque">Naque</option>
                                                    <option value="Natalandia">Natalandia</option>
                                                    <option value="Natercia">Natercia</option>
                                                    <option value="Nazareno">Nazareno</option>
                                                    <option value="Nepomuceno">Nepomuceno</option>
                                                    <option value="Ninheira">Ninheira</option>
                                                    <option value="Nova Belem">Nova Belem</option>
                                                    <option value="Nova Era">Nova Era</option>
                                                    <option value="Nova Lima">Nova Lima</option>
                                                    <option value="Nova Modica">Nova Modica</option>
                                                    <option value="Nova Ponte">Nova Ponte</option>
                                                    <option value="Nova Porteirinha">Nova Porteirinha</option>
                                                    <option value="Nova Resende">Nova Resende</option>
                                                    <option value="Nova Serrana">Nova Serrana</option>
                                                    <option value="Nova Uniao">Nova Uniao</option>
                                                    <option value="Novo Cruzeiro">Novo Cruzeiro</option>
                                                    <option value="Novo Oriente de Minas">Novo Oriente de Minas</option>
                                                    <option value="Novorizonte">Novorizonte</option>
                                                    <option value="Olaria">Olaria</option>
                                                    <option value="Olhos-d'Agua">Olhos-d'Agua</option>
                                                    <option value="Olimpio Noronha">Olimpio Noronha</option>
                                                    <option value="Oliveira Fortes">Oliveira Fortes</option>
                                                    <option value="Oliveira">Oliveira</option>
                                                    <option value="Onca de Pitangui">Onca de Pitangui</option>
                                                    <option value="Oratorios">Oratorios</option>
                                                    <option value="Orizania">Orizania</option>
                                                    <option value="Ouro Branco">Ouro Branco</option>
                                                    <option value="Ouro Fino">Ouro Fino</option>
                                                    <option value="Ouro Preto">Ouro Preto</option>
                                                    <option value="Ouro Verde de Minas">Ouro Verde de Minas</option>
                                                    <option value="Padre Carvalho">Padre Carvalho</option>
                                                    <option value="Padre Paraiso">Padre Paraiso</option>
                                                    <option value="Pai Pedro">Pai Pedro</option>
                                                    <option value="Paineiras">Paineiras</option>
                                                    <option value="Pains">Pains</option>
                                                    <option value="Paiva">Paiva</option>
                                                    <option value="Palma">Palma</option>
                                                    <option value="Palmopolis">Palmopolis</option>
                                                    <option value="Papagaios">Papagaios</option>
                                                    <option value="Para de Minas">Para de Minas</option>
                                                    <option value="Paracatu">Paracatu</option>
                                                    <option value="Paraguacu">Paraguacu</option>
                                                    <option value="Paraisopolis">Paraisopolis</option>
                                                    <option value="Paraopeba">Paraopeba</option>
                                                    <option value="Passa Quatro">Passa Quatro</option>
                                                    <option value="Passa Tempo">Passa Tempo</option>
                                                    <option value="Passa Vinte">Passa Vinte</option>
                                                    <option value="Passabem">Passabem</option>
                                                    <option value="Passos">Passos</option>
                                                    <option value="Patis">Patis</option>
                                                    <option value="Patos de Minas">Patos de Minas</option>
                                                    <option value="Patrocinio do Muriae">Patrocinio do Muriae</option>
                                                    <option value="Patrocinio">Patrocinio</option>
                                                    <option value="Paula Candido">Paula Candido</option>
                                                    <option value="Paulistas">Paulistas</option>
                                                    <option value="Pavao">Pavao</option>
                                                    <option value="Pecanha">Pecanha</option>
                                                    <option value="Pedra Azul">Pedra Azul</option>
                                                    <option value="Pedra Bonita">Pedra Bonita</option>
                                                    <option value="Pedra Dourada">Pedra Dourada</option>
                                                    <option value="Pedra do Anta">Pedra do Anta</option>
                                                    <option value="Pedra do Indaia">Pedra do Indaia</option>
                                                    <option value="Pedralva">Pedralva</option>
                                                    <option value="Pedras de Maria da Cruz">Pedras de Maria da Cruz</option>
                                                    <option value="Pedrinopolis">Pedrinopolis</option>
                                                    <option value="Pedro Leopoldo">Pedro Leopoldo</option>
                                                    <option value="Pedro Teixeira">Pedro Teixeira</option>
                                                    <option value="Pequeri">Pequeri</option>
                                                    <option value="Pequi">Pequi</option>
                                                    <option value="Perdigao">Perdigao</option>
                                                    <option value="Perdizes">Perdizes</option>
                                                    <option value="Perdoes">Perdoes</option>
                                                    <option value="Periquito">Periquito</option>
                                                    <option value="Pescador">Pescador</option>
                                                    <option value="Piau">Piau</option>
                                                    <option value="Piedade de Caratinga">Piedade de Caratinga</option>
                                                    <option value="Piedade de Ponte Nova">Piedade de Ponte Nova</option>
                                                    <option value="Piedade do Rio Grande">Piedade do Rio Grande</option>
                                                    <option value="Piedade dos Gerais">Piedade dos Gerais</option>
                                                    <option value="Pimenta">Pimenta</option>
                                                    <option value="Pingo d'Agua">Pingo d'Agua</option>
                                                    <option value="Pintopolis">Pintopolis</option>
                                                    <option value="Piracema">Piracema</option>
                                                    <option value="Pirajuba">Pirajuba</option>
                                                    <option value="Piranga">Piranga</option>
                                                    <option value="Pirangucu">Pirangucu</option>
                                                    <option value="Piranguinho">Piranguinho</option>
                                                    <option value="Pirapetinga">Pirapetinga</option>
                                                    <option value="Pirapora">Pirapora</option>
                                                    <option value="Pirauba">Pirauba</option>
                                                    <option value="Pitangui">Pitangui</option>
                                                    <option value="Piui">Piui</option>
                                                    <option value="Planura">Planura</option>
                                                    <option value="Poco Fundo">Poco Fundo</option>
                                                    <option value="Pocos de Caldas">Pocos de Caldas</option>
                                                    <option value="Pocrane">Pocrane</option>
                                                    <option value="Pompeu">Pompeu</option>
                                                    <option value="Ponte Nova">Ponte Nova</option>
                                                    <option value="Ponto Chique">Ponto Chique</option>
                                                    <option value="Ponto dos Volantes">Ponto dos Volantes</option>
                                                    <option value="Porteirinha">Porteirinha</option>
                                                    <option value="Porto Firme">Porto Firme</option>
                                                    <option value="Pote">Pote</option>
                                                    <option value="Pouso Alegre">Pouso Alegre</option>
                                                    <option value="Pouso Alto">Pouso Alto</option>
                                                    <option value="Prados">Prados</option>
                                                    <option value="Prata">Prata</option>
                                                    <option value="Pratapolis">Pratapolis</option>
                                                    <option value="Pratinha">Pratinha</option>
                                                    <option value="Presidente Bernardes">Presidente Bernardes</option>
                                                    <option value="Presidente Juscelino">Presidente Juscelino</option>
                                                    <option value="Presidente Kubitschek">Presidente Kubitschek</option>
                                                    <option value="Presidente Olegario">Presidente Olegario</option>
                                                    <option value="Prudente de Morais">Prudente de Morais</option>
                                                    <option value="Quartel Geral">Quartel Geral</option>
                                                    <option value="Queluzita">Queluzita</option>
                                                    <option value="Raposos">Raposos</option>
                                                    <option value="Raul Soares">Raul Soares</option>
                                                    <option value="Recreio">Recreio</option>
                                                    <option value="Reduto">Reduto</option>
                                                    <option value="Resende Costa">Resende Costa</option>
                                                    <option value="Resplendor">Resplendor</option>
                                                    <option value="Ressaquinha">Ressaquinha</option>
                                                    <option value="Riachinho">Riachinho</option>
                                                    <option value="Riacho dos Machados">Riacho dos Machados</option>
                                                    <option value="Ribeirao Vermelho">Ribeirao Vermelho</option>
                                                    <option value="Ribeirao das Neves">Ribeirao das Neves</option>
                                                    <option value="Rio Acima">Rio Acima</option>
                                                    <option value="Rio Casca">Rio Casca</option>
                                                    <option value="Rio Doce">Rio Doce</option>
                                                    <option value="Rio Espera">Rio Espera</option>
                                                    <option value="Rio Manso">Rio Manso</option>
                                                    <option value="Rio Novo">Rio Novo</option>
                                                    <option value="Rio Paranaiba">Rio Paranaiba</option>
                                                    <option value="Rio Pardo de Minas">Rio Pardo de Minas</option>
                                                    <option value="Rio Piracicaba">Rio Piracicaba</option>
                                                    <option value="Rio Pomba">Rio Pomba</option>
                                                    <option value="Rio Preto">Rio Preto</option>
                                                    <option value="Rio Vermelho">Rio Vermelho</option>
                                                    <option value="Rio do Prado">Rio do Prado</option>
                                                    <option value="Ritapolis">Ritapolis</option>
                                                    <option value="Rochedo de Minas">Rochedo de Minas</option>
                                                    <option value="Rodeiro">Rodeiro</option>
                                                    <option value="Romaria">Romaria</option>
                                                    <option value="Rosario da Limeira">Rosario da Limeira</option>
                                                    <option value="Rubelita">Rubelita</option>
                                                    <option value="Rubim">Rubim</option>
                                                    <option value="Sabara">Sabara</option>
                                                    <option value="Sabinopolis">Sabinopolis</option>
                                                    <option value="Sacramento">Sacramento</option>
                                                    <option value="Salinas">Salinas</option>
                                                    <option value="Salto da Divisa">Salto da Divisa</option>
                                                    <option value="Santa Barbara do Leste">Santa Barbara do Leste</option>
                                                    <option value="Santa Barbara do Monte Verde">Santa Barbara do Monte Verde</option>
                                                    <option value="Santa Barbara do Tugurio">Santa Barbara do Tugurio</option>
                                                    <option value="Santa Barbara">Santa Barbara</option>
                                                    <option value="Santa Cruz de Minas">Santa Cruz de Minas</option>
                                                    <option value="Santa Cruz de Salinas">Santa Cruz de Salinas</option>
                                                    <option value="Santa Cruz do Escalvado">Santa Cruz do Escalvado</option>
                                                    <option value="Santa Efigenia de Minas">Santa Efigenia de Minas</option>
                                                    <option value="Santa Fe de Minas">Santa Fe de Minas</option>
                                                    <option value="Santa Helena de Minas">Santa Helena de Minas</option>
                                                    <option value="Santa Juliana">Santa Juliana</option>
                                                    <option value="Santa Luzia">Santa Luzia</option>
                                                    <option value="Santa Margarida">Santa Margarida</option>
                                                    <option value="Santa Maria de Itabira">Santa Maria de Itabira</option>
                                                    <option value="Santa Maria do Salto">Santa Maria do Salto</option>
                                                    <option value="Santa Maria do Suacui">Santa Maria do Suacui</option>
                                                    <option value="Santa Rita de Caldas">Santa Rita de Caldas</option>
                                                    <option value="Santa Rita de Ibitipoca">Santa Rita de Ibitipoca</option>
                                                    <option value="Santa Rita de Jacutinga">Santa Rita de Jacutinga</option>
                                                    <option value="Santa Rita de Minas">Santa Rita de Minas</option>
                                                    <option value="Santa Rita do Itueto">Santa Rita do Itueto</option>
                                                    <option value="Santa Rita do Sapucai">Santa Rita do Sapucai</option>
                                                    <option value="Santa Rosa da Serra">Santa Rosa da Serra</option>
                                                    <option value="Santa Vitoria">Santa Vitoria</option>
                                                    <option value="Santana da Vargem">Santana da Vargem</option>
                                                    <option value="Santana de Cataguases">Santana de Cataguases</option>
                                                    <option value="Santana de Pirapama">Santana de Pirapama</option>
                                                    <option value="Santana do Deserto">Santana do Deserto</option>
                                                    <option value="Santana do Garambeu">Santana do Garambeu</option>
                                                    <option value="Santana do Jacare">Santana do Jacare</option>
                                                    <option value="Santana do Manhuacu">Santana do Manhuacu</option>
                                                    <option value="Santana do Paraiso">Santana do Paraiso</option>
                                                    <option value="Santana do Riacho">Santana do Riacho</option>
                                                    <option value="Santana dos Montes">Santana dos Montes</option>
                                                    <option value="Santo Antonio do Amparo">Santo Antonio do Amparo</option>
                                                    <option value="Santo Antonio do Aventureiro">Santo Antonio do Aventureiro</option>
                                                    <option value="Santo Antonio do Grama">Santo Antonio do Grama</option>
                                                    <option value="Santo Antonio do Itambe">Santo Antonio do Itambe</option>
                                                    <option value="Santo Antonio do Jacinto">Santo Antonio do Jacinto</option>
                                                    <option value="Santo Antonio do Monte">Santo Antonio do Monte</option>
                                                    <option value="Santo Antonio do Retiro">Santo Antonio do Retiro</option>
                                                    <option value="Santo Antonio do Rio Abaixo">Santo Antonio do Rio Abaixo</option>
                                                    <option value="Santo Hipolito">Santo Hipolito</option>
                                                    <option value="Santos Dumont">Santos Dumont</option>
                                                    <option value="Sao Bento Abade">Sao Bento Abade</option>
                                                    <option value="Sao Bras do Suacui">Sao Bras do Suacui</option>
                                                    <option value="Sao Domingos das Dores">Sao Domingos das Dores</option>
                                                    <option value="Sao Domingos do Prata">Sao Domingos do Prata</option>
                                                    <option value="Sao Felix de Minas">Sao Felix de Minas</option>
                                                    <option value="Sao Francisco de Paula">Sao Francisco de Paula</option>
                                                    <option value="Sao Francisco de Sales">Sao Francisco de Sales</option>
                                                    <option value="Sao Francisco do Gloria">Sao Francisco do Gloria</option>
                                                    <option value="Sao Francisco">Sao Francisco</option>
                                                    <option value="Sao Geraldo da Piedade">Sao Geraldo da Piedade</option>
                                                    <option value="Sao Geraldo do Baixio">Sao Geraldo do Baixio</option>
                                                    <option value="Sao Geraldo">Sao Geraldo</option>
                                                    <option value="Sao Goncalo do Abaete">Sao Goncalo do Abaete</option>
                                                    <option value="Sao Goncalo do Para">Sao Goncalo do Para</option>
                                                    <option value="Sao Goncalo do Rio Abaixo">Sao Goncalo do Rio Abaixo</option>
                                                    <option value="Sao Goncalo do Rio Preto">Sao Goncalo do Rio Preto</option>
                                                    <option value="Sao Goncalo do Sapucai">Sao Goncalo do Sapucai</option>
                                                    <option value="Sao Gotardo">Sao Gotardo</option>
                                                    <option value="Sao Joao Batista do Gloria">Sao Joao Batista do Gloria</option>
                                                    <option value="Sao Joao Evangelista">Sao Joao Evangelista</option>
                                                    <option value="Sao Joao Nepomuceno">Sao Joao Nepomuceno</option>
                                                    <option value="Sao Joao da Lagoa">Sao Joao da Lagoa</option>
                                                    <option value="Sao Joao da Mata">Sao Joao da Mata</option>
                                                    <option value="Sao Joao da Ponte">Sao Joao da Ponte</option>
                                                    <option value="Sao Joao das Missoes">Sao Joao das Missoes</option>
                                                    <option value="Sao Joao del Rei">Sao Joao del Rei</option>
                                                    <option value="Sao Joao do Manhuacu">Sao Joao do Manhuacu</option>
                                                    <option value="Sao Joao do Manteninha">Sao Joao do Manteninha</option>
                                                    <option value="Sao Joao do Oriente">Sao Joao do Oriente</option>
                                                    <option value="Sao Joao do Pacui">Sao Joao do Pacui</option>
                                                    <option value="Sao Joao do Paraiso">Sao Joao do Paraiso</option>
                                                    <option value="Sao Joaquim de Bicas">Sao Joaquim de Bicas</option>
                                                    <option value="Sao Jose da Barra">Sao Jose da Barra</option>
                                                    <option value="Sao Jose da Lapa">Sao Jose da Lapa</option>
                                                    <option value="Sao Jose da Safira">Sao Jose da Safira</option>
                                                    <option value="Sao Jose da Varginha">Sao Jose da Varginha</option>
                                                    <option value="Sao Jose do Alegre">Sao Jose do Alegre</option>
                                                    <option value="Sao Jose do Divino">Sao Jose do Divino</option>
                                                    <option value="Sao Jose do Goiabal">Sao Jose do Goiabal</option>
                                                    <option value="Sao Jose do Jacuri">Sao Jose do Jacuri</option>
                                                    <option value="Sao Jose do Mantimento">Sao Jose do Mantimento</option>
                                                    <option value="Sao Lourenco">Sao Lourenco</option>
                                                    <option value="Sao Miguel do Anta">Sao Miguel do Anta</option>
                                                    <option value="Sao Pedro da Uniao">Sao Pedro da Uniao</option>
                                                    <option value="Sao Pedro do Suacui">Sao Pedro do Suacui</option>
                                                    <option value="Sao Pedro dos Ferros">Sao Pedro dos Ferros</option>
                                                    <option value="Sao Romao">Sao Romao</option>
                                                    <option value="Sao Roque de Minas">Sao Roque de Minas</option>
                                                    <option value="Sao Sebastiao da Bela Vista">Sao Sebastiao da Bela Vista</option>
                                                    <option value="Sao Sebastiao da Vargem Alegre">Sao Sebastiao da Vargem Alegre</option>
                                                    <option value="Sao Sebastiao do Anta">Sao Sebastiao do Anta</option>
                                                    <option value="Sao Sebastiao do Maranhao">Sao Sebastiao do Maranhao</option>
                                                    <option value="Sao Sebastiao do Oeste">Sao Sebastiao do Oeste</option>
                                                    <option value="Sao Sebastiao do Paraiso">Sao Sebastiao do Paraiso</option>
                                                    <option value="Sao Sebastiao do Rio Preto">Sao Sebastiao do Rio Preto</option>
                                                    <option value="Sao Sebastiao do Rio Verde">Sao Sebastiao do Rio Verde</option>
                                                    <option value="Sao Thome das Letras">Sao Thome das Letras</option>
                                                    <option value="Sao Tiago">Sao Tiago</option>
                                                    <option value="Sao Tomas de Aquino">Sao Tomas de Aquino</option>
                                                    <option value="Sao Vicente de Minas">Sao Vicente de Minas</option>
                                                    <option value="Sapucai-Mirim">Sapucai-Mirim</option>
                                                    <option value="Sardoa">Sardoa</option>
                                                    <option value="Sarzedo">Sarzedo</option>
                                                    <option value="Sem-Peixe">Sem-Peixe</option>
                                                    <option value="Senador Amaral">Senador Amaral</option>
                                                    <option value="Senador Cortes">Senador Cortes</option>
                                                    <option value="Senador Firmino">Senador Firmino</option>
                                                    <option value="Senador Jose Bento">Senador Jose Bento</option>
                                                    <option value="Senador Modestino Goncalves">Senador Modestino Goncalves</option>
                                                    <option value="Senhora de Oliveira">Senhora de Oliveira</option>
                                                    <option value="Senhora do Porto">Senhora do Porto</option>
                                                    <option value="Senhora dos Remedios">Senhora dos Remedios</option>
                                                    <option value="Sericita">Sericita</option>
                                                    <option value="Seritinga">Seritinga</option>
                                                    <option value="Serra Azul de Minas">Serra Azul de Minas</option>
                                                    <option value="Serra da Saudade">Serra da Saudade</option>
                                                    <option value="Serra do Salitre">Serra do Salitre</option>
                                                    <option value="Serra dos Aimores">Serra dos Aimores</option>
                                                    <option value="Serrania">Serrania</option>
                                                    <option value="Serranopolis de Minas">Serranopolis de Minas</option>
                                                    <option value="Serranos">Serranos</option>
                                                    <option value="Serro">Serro</option>
                                                    <option value="Sete Lagoas">Sete Lagoas</option>
                                                    <option value="Setubinha">Setubinha</option>
                                                    <option value="Silveirania">Silveirania</option>
                                                    <option value="Silvianopolis">Silvianopolis</option>
                                                    <option value="Simao Pereira">Simao Pereira</option>
                                                    <option value="Simonesia">Simonesia</option>
                                                    <option value="Sobralia">Sobralia</option>
                                                    <option value="Soledade de Minas">Soledade de Minas</option>
                                                    <option value="Tabuleiro">Tabuleiro</option>
                                                    <option value="Taiobeiras">Taiobeiras</option>
                                                    <option value="Taparuba">Taparuba</option>
                                                    <option value="Tapira">Tapira</option>
                                                    <option value="Tapirai">Tapirai</option>
                                                    <option value="Taquaracu de Minas">Taquaracu de Minas</option>
                                                    <option value="Tarumirim">Tarumirim</option>
                                                    <option value="Teixeiras">Teixeiras</option>
                                                    <option value="Teofilo Otoni">Teofilo Otoni</option>
                                                    <option value="Timoteo">Timoteo</option>
                                                    <option value="Tiradentes">Tiradentes</option>
                                                    <option value="Tiros">Tiros</option>
                                                    <option value="Tocantins">Tocantins</option>
                                                    <option value="Tocos do Moji">Tocos do Moji</option>
                                                    <option value="Toledo">Toledo</option>
                                                    <option value="Tombos">Tombos</option>
                                                    <option value="Tres Coracoes">Tres Coracoes</option>
                                                    <option value="Tres Marias">Tres Marias</option>
                                                    <option value="Tres Pontas">Tres Pontas</option>
                                                    <option value="Tumiritinga">Tumiritinga</option>
                                                    <option value="Tupaciguara">Tupaciguara</option>
                                                    <option value="Turmalina">Turmalina</option>
                                                    <option value="Turvolandia">Turvolandia</option>
                                                    <option value="Uba">Uba</option>
                                                    <option value="Ubai">Ubai</option>
                                                    <option value="Ubaporanga">Ubaporanga</option>
                                                    <option value="Uberaba">Uberaba</option>
                                                    <option value="Uberlandia">Uberlandia</option>
                                                    <option value="Umburatiba">Umburatiba</option>
                                                    <option value="Unai">Unai</option>
                                                    <option value="Uniao de Minas">Uniao de Minas</option>
                                                    <option value="Uruana de Minas">Uruana de Minas</option>
                                                    <option value="Urucania">Urucania</option>
                                                    <option value="Urucuia">Urucuia</option>
                                                    <option value="Vargem Alegre">Vargem Alegre</option>
                                                    <option value="Vargem Bonita">Vargem Bonita</option>
                                                    <option value="Vargem Grande do Rio Pardo">Vargem Grande do Rio Pardo</option>
                                                    <option value="Varginha">Varginha</option>
                                                    <option value="Varjao de MInas">Varjao de MInas</option>
                                                    <option value="Varzea da Palma">Varzea da Palma</option>
                                                    <option value="Varzelandia">Varzelandia</option>
                                                    <option value="Vazante">Vazante</option>
                                                    <option value="Verdelandia">Verdelandia</option>
                                                    <option value="Veredinha">Veredinha</option>
                                                    <option value="Verissimo">Verissimo</option>
                                                    <option value="Vermelho Novo">Vermelho Novo</option>
                                                    <option value="Vespasiano">Vespasiano</option>
                                                    <option value="Vicosa">Vicosa</option>
                                                    <option value="Vieiras">Vieiras</option>
                                                    <option value="Virgem da Lapa">Virgem da Lapa</option>
                                                    <option value="Virginia">Virginia</option>
                                                    <option value="Virginopolis">Virginopolis</option>
                                                    <option value="Virgolandia">Virgolandia</option>
                                                    <option value="Visconde do Rio Branco">Visconde do Rio Branco</option>
                                                    <option value="Volta Grande">Volta Grande</option>
                                                    <option value="Wenceslau Braz">Wenceslau Braz</option>
                                                </select>
                </td>
           </tr>

            <tr>    
                <td>
                    <label for="bairro">Bairro </label>
                </td>
                <td>
                    <input type="text" name="bairro" id="bairro" size="30" value="{$obj.bairro}"  />
                </td>

            </tr>
            <tr>    
                <td>
                    <label for="endereco">Endereço</label>
                </td>
                <td>
                    <input type="text" name="endereco" id="endereco" size="30" value="{$obj.endereco}" />
                </td>        
            </tr>
            
        </table>
        
        </div>
        <div  style="padding:5px">
            <label for='nsmodem'>Observações</label>
            <hr/>
            <table class="tbForm">
                <tr>    
                  <td >
                      <textarea id="observacoes" name="observacoes" cols="45" rows="8"></textarea>
                  </td>

                 </tr>

            </table>
        </div>
        <div style="clear: both"></div>
        <div class="divObs"> * Campos marcados em vermelho são obrigatórios.</div>
    </fieldset> 
     <br />
    <center><input type="button" value="Salvar" onClick="javascript:sendPost('Realocacao/edit','fRelEdit')" /></center>
</form>
</center>